# cloudbuild.yaml
steps:
- name: node:12.16.1
  entrypoint: npm
  args: ["install"]
- name: node:12.16.1
  entrypoint: npm
  args: [ "start","build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"