
import './js/start.js'
import './js/ParticlesConfig'
import './js/ButtonHandlers'
import './js/hashListener.js'
import './pages/dashboard/dashboard'
import './pages/users/users'
import './pages/user_dashboard/user_dashboard'
import './pages/dashboard/add_admin'
import './styles/main.css'