import './js/ParticlesConfig'
import './js/ButtonHandlers'
import './js/router.js'
import './js/UserManager.js'
import './js/config'
import './styles/main.css'
// import './pages/sample/blockly.min.js'
// import './pages/sample/blockly_compressed'
// import './pages/sample/javascript_compressed'
//import './pages/blockly/js/en.js'
